site:
  name: Together ADHD
  email: info@togetheradhd.co.uk
  ico_registration: "00010615323"
  waitlist_only: false
logo:
  light: ~/assets/images/adhd/together-logo.png
  dark: ~/assets/images/adhd/together-logo.png
  alt: Together ADHD Logo
footer:
  title: Together ADHD
  business_info: Sole trader, trading as Together ADHD. North Lincolnshire and
    surrounding areas.
seo:
  title_default: Together ADHD Assessments
  title_template: "%s â€” Together ADHD Assessments"
  description: ADHD assessments for adults in the UK. Professional neurodiversity
    assessment services for North Lincolnshire and surrounding areas.
  robots_index: false
  robots_follow: true
  area_served: North Lincolnshire
  social:
    linkedin: ""
    twitter: ""
    facebook: ""
  business:
    founding_date: ""
    legal_name: ""
    vat_id: ""
    location:
      street_address: ""
      address_locality: ""
      address_region: North Lincolnshire
      postal_code: ""
      latitude: null
      longitude: null
analytics:
  ga4_id: ""
